[package]
name = "chess-lib"
version = "1.0.0"
authors = ["Mario Reder <mario.reder@pm.me>"]
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
near-contract-standards = "4"
near-sdk = "4"
thiserror = "1"
witgen = "0.15"

[dependencies.chess-engine]
version = "0.1"
path = "../../../chess-engine"

[package.metadata.witgen]
export = true
