[package]
name = "test-token"
version = "0.1.0"
authors = ["Mario Reder <mario.reder@pm.me>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-contract-standards.workspace = true


[dependencies.near-sdk]
workspace = true
features = ["unit-testing"]
