[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
either = "1"
futures = "0.3"
maplit = "1"
near-workspaces = { version = "0.10", default-features = false }
owo-colors = "4"
primitive-types = { version = "0.12", default-features = false }
rand = { version = "0.8", default-features = false, features = ["alloc"] }
rand_chacha = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
toml = "0.8"
urlencoding = "2"

[workspace.dependencies.near-contract-standards]
version = "5.0.0-alpha.2"

[workspace.dependencies.near-sdk]
version = "5.0.0-alpha.2"
default-features = false
features = ["unit-testing", "unstable"]

[profile]
[profile.release]
codegen-units = 1
opt-level = 3
lto = true
debug = false
panic = "abort"
overflow-checks = true
strip = "symbols"

[profile.test.package.'*']
codegen-units = 1
opt-level = 1
