/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "Achievement".
 */
export type Achievement =
  | 'FirstWin'
  | 'FirstWinAiEasy'
  | 'FirstWinAiMedium'
  | 'FirstWinAiHard'
  | 'FirstWinAiVeryHard'
  | 'Wins10'
  | 'Wins50'
  | 'Wins100'
  | 'Wins500'
  | 'WinStreak3'
  | 'WinStreak5'
  | 'WinStreak10'
  | 'WinStreak25'
  | 'FirstBet'
  | 'FirstBetWin'
  | 'BetsWon10'
  | 'BetsWon100'
  | 'FirstWager'
  | 'FirstWagerWin'
  | 'WagerWins10'
  | 'WagerWins100'
  | 'Elo1100'
  | 'Elo1200'
  | 'Elo1300'
  | 'Elo1400'
  | 'Elo1500'
  | 'FirstChallenge'
  | 'Challenges10'
  | 'Challenges100';
/**
 * Helper class to serialize/deserialize `Vec<u8>` to base64 string.
 *
 * # Example ```rust use near_sdk::{json_types::Base64VecU8, near};
 *
 * #[near(serializers=[json])] struct NewStruct { field: Base64VecU8, } ```
 *
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "Base64VecU8".
 */
export type Base64VecU8 = number[];
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "Color".
 */
export type Color = 'White' | 'Black';
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "Difficulty".
 */
export type Difficulty = 'Easy' | 'Medium' | 'Hard' | 'VeryHard';
/**
 * @minItems 3
 * @maxItems 3
 *
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "GameId".
 */
export type GameId = [number, string, string | null];
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "Player".
 */
export type Player =
  | {
      type: 'Human';
      /**
       * NEAR Account Identifier.
       *
       * This is a unique, syntactically valid, human-readable account identifier on the NEAR network.
       *
       * [See the crate-level docs for information about validation.](index.html#account-id-rules)
       *
       * Also see [Error kind precedence](AccountId#error-kind-precedence).
       *
       * ## Examples
       *
       * ``` use near_account_id::AccountId;
       *
       * let alice: AccountId = "alice.near".parse().unwrap();
       *
       * assert!("ƒelicia.near".parse::<AccountId>().is_err()); // (ƒ is not f) ```
       */
      value: string;
      [k: string]: unknown;
    }
  | {
      type: 'Ai';
      value: Difficulty;
      [k: string]: unknown;
    };
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "GameOutcome".
 */
export type GameOutcome =
  | {
      color: Color;
      result: 'Victory';
      [k: string]: unknown;
    }
  | {
      result: 'Stalemate';
      [k: string]: unknown;
    };
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "PromiseOrValueNull".
 */
export type PromiseOrValueNull = null;
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "PromiseOrValueString".
 */
export type PromiseOrValueString = string;
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "Quest".
 */
export type Quest =
  | 'DailyPlayMove'
  | 'DailyGame'
  | 'WeeklyWin'
  | 'WeeklyBettor'
  | 'WeeklyChallenger';

export interface ContractTypes {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "AccountInfo".
 */
export interface AccountInfo {
  bets_placed: number;
  bets_won: number;
  challenges_sent: number;
  elo?: number | null;
  is_agent: boolean;
  max_win_streak: number;
  near_amount: string;
  pending_points: string;
  points: string;
  wager_wins: number;
  wagers_played: number;
  win_streak: number;
  wins: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "AchievementInfo".
 */
export interface AchievementInfo {
  name: string;
  points: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "BetInfo".
 */
export interface BetInfo {
  bets: {
    [k: string]: [string, BetView][];
  };
  is_locked: boolean;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "BetView".
 */
export interface BetView {
  amount: string;
  /**
   * NEAR Account Identifier.
   *
   * This is a unique, syntactically valid, human-readable account identifier on the NEAR network.
   *
   * [See the crate-level docs for information about validation.](index.html#account-id-rules)
   *
   * Also see [Error kind precedence](AccountId#error-kind-precedence).
   *
   * ## Examples
   *
   * ``` use near_account_id::AccountId;
   *
   * let alice: AccountId = "alice.near".parse().unwrap();
   *
   * assert!("ƒelicia.near".parse::<AccountId>().is_err()); // (ƒ is not f) ```
   */
  winner: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "Challenge".
 */
export interface Challenge {
  /**
   * NEAR Account Identifier.
   *
   * This is a unique, syntactically valid, human-readable account identifier on the NEAR network.
   *
   * [See the crate-level docs for information about validation.](index.html#account-id-rules)
   *
   * Also see [Error kind precedence](AccountId#error-kind-precedence).
   *
   * ## Examples
   *
   * ``` use near_account_id::AccountId;
   *
   * let alice: AccountId = "alice.near".parse().unwrap();
   *
   * assert!("ƒelicia.near".parse::<AccountId>().is_err()); // (ƒ is not f) ```
   */
  challenged: string;
  /**
   * NEAR Account Identifier.
   *
   * This is a unique, syntactically valid, human-readable account identifier on the NEAR network.
   *
   * [See the crate-level docs for information about validation.](index.html#account-id-rules)
   *
   * Also see [Error kind precedence](AccountId#error-kind-precedence).
   *
   * ## Examples
   *
   * ``` use near_account_id::AccountId;
   *
   * let alice: AccountId = "alice.near".parse().unwrap();
   *
   * assert!("ƒelicia.near".parse::<AccountId>().is_err()); // (ƒ is not f) ```
   */
  challenger: string;
  id: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  wager?: [string, string] | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "FungibleTokenMetadata".
 */
export interface FungibleTokenMetadata {
  decimals: number;
  icon?: string | null;
  name: string;
  reference?: string | null;
  reference_hash?: Base64VecU8 | null;
  spec: string;
  symbol: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "GameInfo".
 */
export interface GameInfo {
  black: Player;
  has_bets: boolean;
  last_block_height: number;
  turn_color: Color;
  white: Player;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "QuestInfo".
 */
export interface QuestInfo {
  cooldown: number;
  name: string;
  points: string;
  points_on_cd: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "StorageBalance".
 */
export interface StorageBalance {
  available: string;
  total: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ContractTypes`'s JSON-Schema
 * via the `definition` "StorageBalanceBounds".
 */
export interface StorageBalanceBounds {
  max?: string | null;
  min: string;
  [k: string]: unknown;
}
