#!/usr/bin/env python3
"""Generate deterministic Zobrist keys for the on-chain chess engine.

Outputs crates/chess-engine/src/zobrist_keys.rs.
"""

import random
import pathlib

SEED = 0x70726F746F636F6C207061776E73  # "protocol pawns"

PIECE_TYPES = 6  # pawn, knight, bishop, rook, queen, king
COLORS = 2       # white, black
SQUARES = 64


def main():
    rng = random.Random(SEED)

    piece_keys = [
        [[rng.getrandbits(64) for _ in range(SQUARES)] for _ in range(COLORS)]
        for _ in range(PIECE_TYPES)
    ]
    black_to_move_key = rng.getrandbits(64)
    castling_keys = [rng.getrandbits(64) for _ in range(4)]
    en_passant_file_keys = [rng.getrandbits(64) for _ in range(8)]

    out = pathlib.Path(__file__).parent.parent / "crates" / "chess-engine" / "src" / "zobrist_keys.rs"
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// Auto-generated by scripts/generate_zobrist.py",
        "// Do not edit by hand.",
        "",
        "pub const PIECE_ZOBRIST_KEYS: [[[u64; 64]; 2]; 6] = [",
    ]
    for pt in range(PIECE_TYPES):
        lines.append("    [")
        for c in range(COLORS):
            squares = ", ".join(f"{piece_keys[pt][c][sq]}u64" for sq in range(SQUARES))
            lines.append(f"        [{squares}],")
        lines.append("    ],")
    lines.append("];")
    lines.append("")
    lines.append(f"pub const BLACK_TO_MOVE_ZOBRIST_KEY: u64 = {black_to_move_key}u64;")
    lines.append("")
    castling = ", ".join(f"{k}u64" for k in castling_keys)
    lines.append(f"pub const CASTLING_ZOBRIST_KEYS: [u64; 4] = [{castling}];")
    lines.append("")
    ep = ", ".join(f"{k}u64" for k in en_passant_file_keys)
    lines.append(f"pub const EN_PASSANT_FILE_ZOBRIST_KEYS: [u64; 8] = [{ep}];")
    lines.append("")

    out.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
