[package]
name = "chess-common"
version = "1.0.0"
authors = ["Mario Reder <mario.reder@pm.me>"]
edition = "2021"

[dependencies]
chess-engine = { path = "../chess-engine" }
chess-lib = { path = "../chess-lib" }
near-sdk.workspace = true
owo-colors.workspace = true
serde.workspace = true
