name = "pp-api"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-01-29"
compatibility_flags = ["nodejs_compat"]

routes = [
	{ pattern = "api.protocol-pawns.com", custom_domain = true }
]

[vars]
VAPID_SUBJECT = "mailto:admin@protocol-pawns.com"
VAPID_PUBLIC_KEY = "BM4Wktu_G9xs5JWCqXaQHa2TrGdjIdz6hUF1JrKZUfa43ANx_bZl8_wXj3pnLGr2xNg6Ot12oCqgbhqwEFgVA18"

[triggers]
crons = ["* * * * *"]

[observability]
enabled = true
