name = "pp-api"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-01-29"

routes = [
	{ pattern = "api.protocol-pawns.com", custom_domain = true }
]

[vars]
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these

[durable_objects]
bindings = [
  { name = "GAMES", class_name = "Games" },
  { name = "INFO", class_name = "Info" },
]

[[migrations]]
tag = "v1"
new_classes = ["Games", "Info"]
