name: Audit dependencies

on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

env:
  RUST_TOOLCHAIN: nightly-2024-02-16

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions-rs/toolchain@v1
        name: Install Toolchain
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true

      - uses: actions-rs/cargo@v1
        name: Install Cargo Tools
        with:
          command: install
          args: cargo-audit

      - uses: actions-rs/cargo@v1
        name: Audit
        with:
          command: audit
