name: Test

on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "crates/**/*"
      - "Cargo.toml"
      - "build.sh"
      - "rust-toolchain"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "crates/**/*"
      - "build.sh"
      - "Cargo.toml"
      - "rust-toolchain"

env:
  RUST_TOOLCHAIN: nightly-2023-03-20
  BINARYEN_VERSION: 110

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RUST_BACKTRACE: full

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions-rs/toolchain@v1
        name: Install Toolchain
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          target: wasm32-unknown-unknown
          override: true
          components: rustfmt, clippy

      - name: Install wasm-opt
        run: |
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_${{ env.BINARYEN_VERSION }}/binaryen-version_${{ env.BINARYEN_VERSION }}-x86_64-linux.tar.gz --output binaryen.tar.gz
          tar -zxvf binaryen.tar.gz binaryen-version_${{ env.BINARYEN_VERSION }}/bin/wasm-opt
          mv binaryen-version_${{ env.BINARYEN_VERSION }}/bin/wasm-opt /home/runner/.local/bin/wasm-opt

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: -- -D warnings

      - uses: actions-rs/cargo@v1
        name: Fmt
        with:
          command: fmt
          args: -- --check

      - name: Build
        run: ./build.sh

      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: -- --nocapture
