/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * NEAR Account Identifier.
 *
 * This is a unique, syntactically valid, human-readable account identifier on the NEAR network.
 *
 * [See the crate-level docs for information about validation.](index.html#account-id-rules)
 *
 * Also see [Error kind precedence](AccountId#error-kind-precedence).
 *
 * ## Examples
 *
 * ``` use near_account_id::AccountId;
 *
 * let alice: AccountId = "alice.near".parse().unwrap();
 *
 * assert!("ƒelicia.near".parse::<AccountId>().is_err()); // (ƒ is not f) ```
 */
type AccountId = string;

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

interface AccountInfo {
  elo?: number | null;
  is_human: boolean;
  near_amount: string;
  points: string;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

type Achievement =
  | 'FirstWinHuman'
  | 'FirstWinAiEasy'
  | 'FirstWinAiMedium'
  | 'FirstWinAiHard';

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

interface AchievementInfo {
  name: string;
  points: string;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

interface BetInfo {
  bets: {
    [k: string]: [string, BetView][];
  };
  is_locked: boolean;
}
interface BetView {
  amount: string;
  /**
   * NEAR Account Identifier.
   *
   * This is a unique, syntactically valid, human-readable account identifier on the NEAR network.
   *
   * [See the crate-level docs for information about validation.](index.html#account-id-rules)
   *
   * Also see [Error kind precedence](AccountId#error-kind-precedence).
   *
   * ## Examples
   *
   * ``` use near_account_id::AccountId;
   *
   * let alice: AccountId = "alice.near".parse().unwrap();
   *
   * assert!("ƒelicia.near".parse::<AccountId>().is_err()); // (ƒ is not f) ```
   */
  winner: string;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

interface Challenge {
  /**
   * NEAR Account Identifier.
   *
   * This is a unique, syntactically valid, human-readable account identifier on the NEAR network.
   *
   * [See the crate-level docs for information about validation.](index.html#account-id-rules)
   *
   * Also see [Error kind precedence](AccountId#error-kind-precedence).
   *
   * ## Examples
   *
   * ``` use near_account_id::AccountId;
   *
   * let alice: AccountId = "alice.near".parse().unwrap();
   *
   * assert!("ƒelicia.near".parse::<AccountId>().is_err()); // (ƒ is not f) ```
   */
  challenged: string;
  /**
   * NEAR Account Identifier.
   *
   * This is a unique, syntactically valid, human-readable account identifier on the NEAR network.
   *
   * [See the crate-level docs for information about validation.](index.html#account-id-rules)
   *
   * Also see [Error kind precedence](AccountId#error-kind-precedence).
   *
   * ## Examples
   *
   * ``` use near_account_id::AccountId;
   *
   * let alice: AccountId = "alice.near".parse().unwrap();
   *
   * assert!("ƒelicia.near".parse::<AccountId>().is_err()); // (ƒ is not f) ```
   */
  challenger: string;
  id: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  wager?: [string, string] | null;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The color of a piece.
 */
type Color = 'White' | 'Black';

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * AI difficulty setting.
 *
 * The AI uses the [Minimax algorithm, along with Alpha-Beta pruning](https://github.com/Tarnadas/chess-engine#how-does-it-work) The higher the difficulty the more moves will be calculated in advance.
 *
 * Please be aware, that gas usage increases on higher difficulties: - Easy: ~8TGas - Medium: ~30TGas - Hard: ~110TGas
 */
type Difficulty = 'Easy' | 'Medium' | 'Hard';

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

interface Fees {
  royalties: [string, number][];
  treasury: number;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

interface FungibleTokenMetadata {
  decimals: number;
  icon?: string | null;
  name: string;
  reference?: string | null;
  reference_hash?: string | null;
  spec: string;
  symbol: string;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique game ID, which consists of:
 *
 * - block height - wallet ID, e.g. "my-wallet.near" - enemy wallet ID if player or empty if AI
 *
 * @minItems 3
 * @maxItems 3
 */
type GameId = [number, string, string | null];

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

interface GameInfo {
  black:
    | {
        type: 'Human';
        /**
         * NEAR Account Identifier.
         *
         * This is a unique, syntactically valid, human-readable account identifier on the NEAR network.
         *
         * [See the crate-level docs for information about validation.](index.html#account-id-rules)
         *
         * Also see [Error kind precedence](AccountId#error-kind-precedence).
         *
         * ## Examples
         *
         * ``` use near_account_id::AccountId;
         *
         * let alice: AccountId = "alice.near".parse().unwrap();
         *
         * assert!("ƒelicia.near".parse::<AccountId>().is_err()); // (ƒ is not f) ```
         */
        value: string;
      }
    | {
        type: 'Ai';
        /**
         * AI difficulty setting.
         *
         * The AI uses the [Minimax algorithm, along with Alpha-Beta pruning](https://github.com/Tarnadas/chess-engine#how-does-it-work) The higher the difficulty the more moves will be calculated in advance.
         *
         * Please be aware, that gas usage increases on higher difficulties: - Easy: ~8TGas - Medium: ~30TGas - Hard: ~110TGas
         */
        value: 'Easy' | 'Medium' | 'Hard';
      };
  has_bets: boolean;
  last_block_height: number;
  /**
   * The color of a piece.
   */
  turn_color: 'White' | 'Black';
  white:
    | {
        type: 'Human';
        /**
         * NEAR Account Identifier.
         *
         * This is a unique, syntactically valid, human-readable account identifier on the NEAR network.
         *
         * [See the crate-level docs for information about validation.](index.html#account-id-rules)
         *
         * Also see [Error kind precedence](AccountId#error-kind-precedence).
         *
         * ## Examples
         *
         * ``` use near_account_id::AccountId;
         *
         * let alice: AccountId = "alice.near".parse().unwrap();
         *
         * assert!("ƒelicia.near".parse::<AccountId>().is_err()); // (ƒ is not f) ```
         */
        value: string;
      }
    | {
        type: 'Ai';
        /**
         * AI difficulty setting.
         *
         * The AI uses the [Minimax algorithm, along with Alpha-Beta pruning](https://github.com/Tarnadas/chess-engine#how-does-it-work) The higher the difficulty the more moves will be calculated in advance.
         *
         * Please be aware, that gas usage increases on higher difficulties: - Easy: ~8TGas - Medium: ~30TGas - Hard: ~110TGas
         */
        value: 'Easy' | 'Medium' | 'Hard';
      };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

type GameOutcome =
  | 'Stalemate'
  | {
      /**
       * The color of a piece.
       */
      Victory: 'White' | 'Black';
    };

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

type Player =
  | {
      type: 'Human';
      /**
       * NEAR Account Identifier.
       *
       * This is a unique, syntactically valid, human-readable account identifier on the NEAR network.
       *
       * [See the crate-level docs for information about validation.](index.html#account-id-rules)
       *
       * Also see [Error kind precedence](AccountId#error-kind-precedence).
       *
       * ## Examples
       *
       * ``` use near_account_id::AccountId;
       *
       * let alice: AccountId = "alice.near".parse().unwrap();
       *
       * assert!("ƒelicia.near".parse::<AccountId>().is_err()); // (ƒ is not f) ```
       */
      value: string;
    }
  | {
      type: 'Ai';
      /**
       * AI difficulty setting.
       *
       * The AI uses the [Minimax algorithm, along with Alpha-Beta pruning](https://github.com/Tarnadas/chess-engine#how-does-it-work) The higher the difficulty the more moves will be calculated in advance.
       *
       * Please be aware, that gas usage increases on higher difficulties: - Easy: ~8TGas - Medium: ~30TGas - Hard: ~110TGas
       */
      value: 'Easy' | 'Medium' | 'Hard';
    };

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

type PromiseOrValueNull = null;

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

type PromiseOrValueString = string;

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

type Quest = 'DailyPlayMove' | 'WeeklyWinHuman';

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

interface QuestInfo {
  cooldown: number;
  name: string;
  points: string;
  points_on_cd: string;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

interface StorageBalance {
  available: string;
  total: string;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

interface StorageBalanceBounds {
  max?: string | null;
  min: string;
}

export type {
  AccountId,
  AccountInfo,
  Achievement,
  AchievementInfo,
  BetInfo,
  BetView,
  Challenge,
  Color,
  Difficulty,
  Fees,
  FungibleTokenMetadata,
  GameId,
  GameInfo,
  GameOutcome,
  Player,
  PromiseOrValueNull,
  PromiseOrValueString,
  Quest,
  QuestInfo,
  StorageBalance,
  StorageBalanceBounds
};
